module.exports = [
  { french: "avoir", meaning: "to have", category: "Verbs", example: "J'ai un chat noir.", exampleMeaning: "I have a black cat." },
  { french: "mal", meaning: "bad, badly, wrong", category: "Adjectives", example: "Il se sent mal.", exampleMeaning: "He feels bad/sick." },
  { french: "vraiment", meaning: "really, truly", category: "Adverbs", example: "C'est vraiment magnifique!", exampleMeaning: "It's truly magnificent!" },
  { french: "sens", meaning: "direction, meanings, smell", category: "Nouns", example: "Quel est le sens de cette phrase ? / Le sens de l'odorat.", exampleMeaning: "What is the meaning of this sentence? / The sense of smell." },
  { french: "court", meaning: "run, jogs, is running", category: "Verbs", example: "Il court très vite.", exampleMeaning: "He runs very fast." },
  { french: "couleur", meaning: "color", category: "Nouns", example: "Quelle est ta couleur préférée ?", exampleMeaning: "What is your favorite color?" },
  { french: "jambe", meaning: "leg", category: "Body Parts", example: "Il s'est cassé la jambe.", exampleMeaning: "He broke his leg." },
  { french: "long", meaning: "long", category: "Adjectives", example: "C'est un long voyage.", exampleMeaning: "It's a long journey." },
  { french: "sympa", meaning: "nice", category: "Adjectives", example: "Elle est très sympa.", exampleMeaning: "She is very nice." },
  { french: "nez", meaning: "nose, headland", category: "Body Parts", example: "Il a un grand nez.", exampleMeaning: "He has a big nose." },
  { french: "œil", meaning: "eye", category: "Body Parts", example: "Elle a les yeux bleus.", exampleMeaning: "She has blue eyes." },
  { french: "yeux", meaning: "eyes", category: "Body Parts", example: "Il a de beaux yeux.", exampleMeaning: "He has beautiful eyes." },
  { french: "bouche", meaning: "mouth, lips, covers", category: "Body Parts", example: "Ouvre la bouche.", exampleMeaning: "Open your mouth." },
  { french: "visage", meaning: "face", category: "Body Parts", example: "Elle a un joli visage.", exampleMeaning: "She has a pretty face." },
  { french: "bras", meaning: "arm", category: "Body Parts", example: "Il lève le bras.", exampleMeaning: "He raises his arm." },
  { french: "pied", meaning: "foot", category: "Body Parts", example:  "J'ai mal au pied.", exampleMeaning: "My foot hurts."},
  { french: "droit", meaning: "right, law, straight", category: "Adjectives", example: "Tournez à droite.", exampleMeaning: "Turn right." },
  { french: "oreille", meaning: "ear", category: "Body Parts", example: "Il a mal à l'oreille.", exampleMeaning: "He has an earache." },
  { french: "qu'", meaning: "only, that, than", category: "Other", example: "Je n'ai qu'un frère.", exampleMeaning: "I only have one brother." },
  { french: "papa", meaning: "dad, father, daddy", category: "Family", example: "Mon papa est fort.", exampleMeaning: "My dad is strong." },
  { french: "maman", meaning: "mom, mum, mommy", category: "Family", example: "Ma maman est gentille.", exampleMeaning: "My mom is kind." },
  { french: "moins", meaning: "fewer, less", category: "Adverbs", example: "J'ai moins de temps.", exampleMeaning: "I have less time." },
  { french: "riche", meaning: "rich", category: "Adjectives", example: "Il est très riche.", exampleMeaning: "He is very rich." },
  { french: "mince", meaning: "thin, faint, shoot", category: "Adjectives", example: "Elle est mince.", exampleMeaning: "She is thin." },
  { french: "vieux", meaning: "old", category: "Adjectives", example: "C'est un vieux livre.", exampleMeaning: "It's an old book." },
  { french: "vieil", meaning: "old", category: "Adjectives", example: "Un vieil homme.", exampleMeaning: "An old man." },
  { french: "ciel", meaning: "sky, heaven", category: "Nature", example: "Le ciel est bleu.", exampleMeaning: "The sky is blue." },
  { french: "printemps", meaning: "spring", category: "Seasons", example: "Les fleurs fleurissent au printemps.", exampleMeaning: "Flowers bloom in spring." },
  { french: "décembre", meaning: "December", category: "Months", example: "Noël est en décembre.", exampleMeaning: "Christmas is in December." },
  { french: "gris", meaning: "gray", category: "Colors", example: "Le ciel est gris aujourd'hui.", exampleMeaning: "The sky is gray today." },
  { french: "saison", meaning: "season", category: "Seasons", example: "L'automne est ma saison préférée.", exampleMeaning: "Autumn is my favorite season." },
  { french: "bleu", meaning: "blue, bruise", category: "Colors", example: "La mer est bleue.", exampleMeaning: "The sea is blue." },
  { french: "novembre", meaning: "November", category: "Months", example: "Mon anniversaire est en novembre.", exampleMeaning: "My birthday is in November." },
  { french: "pleuvoir", meaning: "to rain", category: "Weather", example: "Il va pleuvoir demain.", exampleMeaning: "It's going to rain tomorrow." },
  { french: "neiger", meaning: "to snow", category: "Weather", example: "Il neige en hiver.", exampleMeaning: "It snows in winter." },
  { french: "faire", meaning: "to do, (to) make, (to) prepare", category: "Verbs", example: "Je vais faire mes devoirs. / Il fait un gâteau.", exampleMeaning: "I'm going to do my homework. / He's making a cake." },
  { french: "pluie", meaning: "rain", category: "Weather", example: "La pluie tombe.", exampleMeaning: "The rain is falling." },
  { french: "toute la journée", meaning: "all day", category: "Time", example: "Il a plu toute la journée.", exampleMeaning: "It rained all day." },
  { french: "mais", meaning: "but, yet, although", category: "Other", example: "Il fait froid, mais il y a du soleil.", exampleMeaning: "It's cold, but it's sunny." },
  { french: "neige", meaning: "snow, (he/she/it) snows/is snowing, (he/she/it) snows", category: "Weather", example: "La neige est blanche. / Il neige.", exampleMeaning: "The snow is white. / It's snowing." },
  { french: "pleut", meaning: "rains, is raining, rain", category: "Weather", example: "Il pleut beaucoup ici.", exampleMeaning: "It rains a lot here." },
  { french: "soleil", meaning: "sun, Catherine wheel, grand circle", category: "Weather", example: "Le soleil brille.", exampleMeaning: "The sun is shining." },
  { french: "vent", meaning: "wind", category: "Weather", example: "Le vent souffle fort.", exampleMeaning: "The wind is blowing hard." },
  { french: "nuage", meaning: "cloud", category: "Weather", example: "Il y a des nuages dans le ciel.", exampleMeaning: "There are clouds in the sky." },
  { french: "octobre", meaning: "October", category: "Months", example: "Halloween est en octobre.", exampleMeaning: "Halloween is in October." },
  { french: "dehors", meaning: "outside, outside of, apart from", category: "Places", example: "Les enfants jouent dehors.", exampleMeaning: "The children are playing outside." },
  { french: "automne", meaning: "fall, autumn", category: "Seasons", example: "Les feuilles tombent en automne.", exampleMeaning: "The leaves fall in autumn." },
  { french: "août", meaning: "August", category: "Months", example: "Les vacances sont en août.", exampleMeaning: "Vacation is in August." },
  { french: "froid", meaning: "cold, callous, coldness", category: "Weather", example: "Il fait froid aujourd'hui.", exampleMeaning: "It's cold today." },
  { french: "chaud", meaning: "hot, warm, hot / warm", category: "Weather", example: "Il fait chaud en été.", exampleMeaning: "It's hot in summer." },
  { french: "fait", meaning: "is, makes, made", category: "Verbs", example: "Il fait beau. / Elle fait un gâteau.", exampleMeaning: "The weather is nice. / She is making a cake." },
  { french: "beau", meaning: "beautiful, handsome, nice", category: "Weather", example: "Il fait beau temps.", exampleMeaning: "The weather is nice." },
  { french: "en général", meaning: "in general, generally", category: "Adverbs", example: "En général, j'aime le café.", exampleMeaning: "In general, I like coffee." },
  { french: "quart", meaning: "quarter, a quarter-litre bottle, a quarter-litre pitcher", category: "Time", example: "Il est midi et quart.", exampleMeaning: "It's quarter past twelve." },
  { french: "veillent", meaning: "watch", category: "Verbs", example: "Ils veillent tard.", exampleMeaning: "They stay up late." },
 { french: "réveillent", meaning: "awake", category: "Verbs", example: "Ils se réveillent tôt.", exampleMeaning: "They wake up early." },
  { french: "dent", meaning: "tooth", category: "Body Parts", example: "Il se brosse les dents.", exampleMeaning: "He brushes his teeth." },
  { french: "coucher", meaning: "put ... to bed", category: "Verbs", example: "Je vais coucher les enfants.", exampleMeaning: "I'm going to put the children to bed." },
  { french: "vite", meaning: "fast, quickly, rapidly", category: "Adverbs", example: "Il court très vite.", exampleMeaning: "He runs very fast." },
  { french: "préparez", meaning: "make, are making, prepare", category: "Verbs", example: "Vous préparez le dîner.", exampleMeaning: "You are making dinner." },
  { french: "cheveux", meaning: "hair, hairs", category: "Body Parts", example: "Elle a les cheveux longs.", exampleMeaning: "She has long hair." },
  { french: "brosser", meaning: "brushing, to brush, brush", category: "Verbs", example: "Je vais me brosser les cheveux.", exampleMeaning: "I'm going to brush my hair." },
  { french: "regardons", meaning: "look at, look, let's watch", category: "Verbs", example: "Nous regardons un film.", exampleMeaning: "We are watching a movie." },
   { french: "demie", meaning: "thirty, half", category: "Time", example: "Il est deux heures et demie.", exampleMeaning: "It's half past two." },
  { french: "te", meaning: "you, yourself, to you", category: "Pronouns", example: "Je te vois.", exampleMeaning: "I see you." },
  { french: "se", meaning: "themselves, himself, oneself", category: "Pronouns", example: "Ils se lavent.", exampleMeaning: "They wash themselves." },
  { french: "me", meaning: "I, at me, me", category: "Pronouns", example: "Tu me parles.", exampleMeaning: "You're talking to me." },
  { french: "réveiller", meaning: "wake up, waking", category: "Verbs", example: "Je vais me réveiller tôt.", exampleMeaning: "I'm going to wake up early." },
  { french: "miroir", meaning: "mirror, glass", category: "Household", example: "Elle se regarde dans le miroir.", exampleMeaning: "She looks at herself in the mirror." },
  { french: "faites-vous", meaning: 'are you doing, are you (ref to "size"), do you do', category: "Questions", example: "Que faites-vous ?", exampleMeaning: "What are you doing?" },
  { french: "fais-tu", meaning: "are you doing", category: "Questions", example: "Que fais-tu ?", exampleMeaning: "What are you doing?" },
  { french: "le soir", meaning: "in the evening, at night", category: "Time", example: "Je rentre tard le soir.", exampleMeaning: "I come home late at night." },
  { french: "que", meaning: "that, what, than", category: "Questions", example: "Que fais-tu ? / C'est plus grand que ça.", exampleMeaning: "What are you doing? / It's bigger than that." },
  { french: "d'habitude", meaning: "usually", category: "Adverbs", example: "Je me lève tôt d'habitude.", exampleMeaning: "I usually get up early." },
  { french: "sport", meaning: "sports, exercise, sport", category: "Activities", example: "Je fais du sport.", exampleMeaning: "I do sports/exercise." },
  { french: "le matin", meaning: "in the morning", category: "Time", example: "Je travaille le matin.", exampleMeaning: "I work in the morning." },
  { french: "fais", meaning: "am making, are doing, done", category: "Verbs", example: "Je fais mes devoirs.", exampleMeaning: "I'm doing my homework." },
  { french: "toujours", meaning: "always, still, anyway", category: "Adverbs", example: "Je suis toujours là pour toi.", exampleMeaning: "I'm always here for you." },
  { french: "faites", meaning: "made, packed, are doing", category: "Verbs", example: "Vous faites du bon travail.", exampleMeaning: "You are doing a good job." },
 { french: "bain", meaning: "bath", category: "Bathroom", example: "Je prends un bain.", exampleMeaning: "I'm taking a bath." },
  { french: "animaux", meaning: "animals, animals'", category: "Animals", example: "J'aime les animaux.", exampleMeaning: "I love animals." },
  { french: "voici", meaning: "here is, here are, this is", category: "Other", example: "Voici votre café.", exampleMeaning: "Here is your coffee." },
  { french: "géniaux", meaning: "great, fantastic", category: "Adjectives", example: "Ce sont des films géniaux.", exampleMeaning: "These are great movies." },
  { french: "juillet", meaning: "July", category: "Months", example: "Mon anniversaire est en juillet.", exampleMeaning: "My birthday is in July." },
  { french: "journaux", meaning: "newspapers", category: "Reading Materials", example: "Il lit les journaux.", exampleMeaning: "He reads the newspapers." },
  { french: "interdit", meaning: "prohibited, forbidden, banned", category: "Other", example: "Il est interdit de fumer ici.", exampleMeaning: "Smoking is prohibited here." },
  { french: "réception", meaning: "front desk, reception", category: "Hotel", example: "La réception est ouverte 24h/24.", exampleMeaning: "The front desk is open 24/7." },
  { french: "animal", meaning: "animal", category: "Animals", example: "Le chien est un animal.", exampleMeaning: "The dog is an animal." },
  { french: "wi-fi", meaning: "Wi-Fi", category: "Hotel", example: "Le mot de passe du wi-fi est...", exampleMeaning: "The Wi-Fi password is..." },
  { french: "génial", meaning: "brilliant, awesome, great", category: "Adjectives", example: "C'est une idée géniale !", exampleMeaning: "That's a brilliant idea!" },
  { french: "non-fumeur", meaning: "non-smoking", category: "Hotel", example: "C'est une chambre non-fumeur.", exampleMeaning: "It's a non-smoking room." },
  { french: "mot de passe", meaning: "password", category: "Other", example: "Quel est le mot de passe ?", exampleMeaning: "What is the password?" },
  { french: "compris", meaning: "understood, included, figuring", category: "Other", example: "J'ai compris. / Tout compris.", exampleMeaning: "I understood. / All inclusive." },
  { french: "mai", meaning: "May", category: "Months", example: "Le premier mai est un jour férié.", exampleMeaning : "May 1st is a holiday." },
  { french: "juin", meaning: "June", category: "Months", example: "L'été commence en juin.", exampleMeaning: "Summer begins in June." },
  { french: "douche", meaning: "shower", category: "Bathroom", example: "Je prends une douche.", exampleMeaning: "I'm taking a shower." },
  { french: "propre", meaning: "own, clean", category: "Adjectives", example: "C'est ma propre voiture. / La chambre est propre.", exampleMeaning: "It's my own car. / The room is clean." },
  { french: "simple", meaning: "simple, straight", category: "Adjectives", example: "C'est une question simple.", exampleMeaning: "It's a simple question." },
  { french: "double", meaning: "double, pass", category: "Hotel", example: "Je voudrais une chambre double.", exampleMeaning: "I would like a double room." },
  { french: "combien de", meaning: "how many", category: "Questions", example: "Combien de frères as-tu ?", exampleMeaning: "How many brothers do you have?" },
  { french: "nuits", meaning: "nights, night", category: "Time", example: "Je reste trois nuits.", exampleMeaning: "I'm staying for three nights." },
  { french: "télévision", meaning: "TV, television", category: "Hotel", example: "Il y a une télévision dans la chambre.", exampleMeaning: "There is a TV in the room." },
  { french: "adresse", meaning: "address", category: "Other", example: "Quelle est votre adresse ?", exampleMeaning: "What is your address?" },
  { french: "réserver", meaning: "to book", category: "Verbs", example: "Je voudrais réserver une table.", exampleMeaning: "I would like to book a table." },
  { french: "clé", meaning: "key", category: "Hotel", example: "Voici la clé de votre chambre.", exampleMeaning: "Here is the key to your room." },
  { french: "serviette", meaning: "napkin, towel", category: "Restaurant", example: "J'ai besoin d'une serviette.", exampleMeaning: "I need a napkin/towel." },
  { french: "joli", meaning: "pretty, lovely", category: "Adjectives", example: "C'est un joli jardin.", exampleMeaning: "It's a pretty garden." },
  { french: "choisissent", meaning: "choose, are choosing", category: "Verbs", example: "Ils choisissent un film.", exampleMeaning: "They are choosing a movie." },
  { french: "leurs", meaning: "their", category: "Pronouns", example: "Ce sont leurs livres.", exampleMeaning: "These are their books." },
  { french: "finit", meaning: "finishes, is finishing, ends", category: "Verbs", example: "Il finit son travail.", exampleMeaning: "He finishes his work." },
  { french: "leur", meaning: "their, them", category: "Pronouns", example: "C'est leur maison. / Je leur parle.", exampleMeaning: "It's their house. / I'm talking to them." },
  { french: "choisit", meaning: "chooses, is choosing, choose", category: "Verbs", example: "Elle choisit une robe.", exampleMeaning: "She chooses a dress." },
  { french: "finissent", meaning: "finish, are finishing, finishing", category: "Verbs", example: "Ils finissent leurs devoirs.", exampleMeaning: "They are finishing their homework." },
  { french: "idée", meaning: "idea, thought", category: "Other", example: "C'est une bonne idée.", exampleMeaning: "That's a good idea." },
  { french: "finissez", meaning: "finish, are finishing, finishing", category: "Verbs", example: "Vous finissez votre repas.", exampleMeaning: "You are finishing your meal." },
  { french: "finissons", meaning: "finish, are finishing", category: "Verbs", example: "Nous finissons le travail.", exampleMeaning: "We are finishing the work." },
  { french: "choisissons", meaning: "choose, are choosing, let's choose", category: "Verbs", example: "Nous choisissons un restaurant.", exampleMeaning: "We are choosing a restaurant." },
  { french: "dix-neuf", meaning: "nineteen", category: "Numbers", example: "J'ai dix-neuf ans.", exampleMeaning: "I am nineteen years old." },
  { french: "choisissez", meaning: "choose, are choosing", category: "Verbs", example: "Vous choisissez un cadeau.", exampleMeaning: "You are choosing a gift." },
  { french: "avril", meaning: "April", category: "Months", example: "Pâques est en avril.", exampleMeaning: "Easter is in April." },
  { french: "date", meaning: "date", category: "Time", example: "Quelle est la date d'aujourd'hui ?", exampleMeaning: "What is the date today?" },
  { french: "besoin de", meaning: "need", category: "Other", example: "J'ai besoin de repos.", exampleMeaning: "I need rest." },
  { french: "choisis", meaning: "choose, are choosing, am choosing", category: "Verbs", example: "Je choisis ce livre.", exampleMeaning: "I choose this book." },
  { french: "finis", meaning: "finish, no more, am finishing", category: "Verbs", example: "Je finis mon travail.", exampleMeaning: "I am finishing my work." },
  { french: "horaire", meaning: "schedule, timetable, time", category: "Time", example: "Quel est l'horaire du train ?", exampleMeaning: "What is the train schedule?" },
  { french: "dix-huit", meaning: "eighteen, 18", category: "Numbers", example: "Il a dix-huit ans.", exampleMeaning: "He is eighteen years old." },
  { french: "choisir", meaning: "to choose, (to) select, go", category: "Verbs", example: "Je vais choisir un dessert.", exampleMeaning: "I'm going to choose a dessert." },
  { french: "jet", meaning: "cast", category: "Other", example: "Il a jeté la balle.", exampleMeaning: "He threw the ball. " },
  { french: "as besoin", meaning: "need", category: "Other", example: "Tu as besoin d'aide ?", exampleMeaning: "Do you need help?" },
  { french: "finir", meaning: "to finish, (to) end, (to) complete", category: "Verbs", example: "Je vais finir mon livre.", exampleMeaning: "I'm going to finish my book." },
  { french: "projet", meaning: "project, plan", category: "School", example: "J'ai un projet à l'école.", exampleMeaning: "I have a project at school." },
  { french: "chef", meaning: "chef, boss", category: "Work", example: "Mon chef est sympathique.", exampleMeaning: "My boss is nice." },
  { french: "mars", meaning: "March, Mars", category: "Months", example: "Mars est le troisième mois de l'année.", exampleMeaning: "March is the third month of the year." },
  { french: "seize", meaning: "sixteen, 16", category: "Numbers", example: "Elle a seize ans.", exampleMeaning: "She is sixteen years old." },
  { french: "besoin", meaning: "need", category: "Other", example: "J'ai besoin d'un café.", exampleMeaning: "I need a coffee." },
  { french: "dix-sept", meaning: "seventeen", category: "Numbers", example: "Il a dix-sept ans.", exampleMeaning: "He is seventeen years old." },
  { french: "réunion", meaning: "Réunion (island), meeting", category: "Work", example: "J'ai une réunion demain.", exampleMeaning: "I have a meeting tomorrow." },
  { french: "salle", meaning: "room", category: "Places", example: "La salle de classe est grande.", exampleMeaning: "The classroom is big." },
  { french: "lentement", meaning: "slowly", category: "Adverbs", example: "Il parle lentement.", exampleMeaning: "He speaks slowly." },
  { french: "comprenons", meaning: "understand", category: "Verbs", example: "Nous comprenons le français.", exampleMeaning: "We understand French." },
  { french: "apprenons", meaning: "are learning, learn, study", category: "Verbs", example: "Nous apprenons une nouvelle langue.", exampleMeaning: "We are learning a new language." },
  { french: "sac à dos", meaning: "backpack", category: "School", example: "J'ai un nouveau sac à dos.", exampleMeaning: "I have a new backpack." },
  { french: "salle de classe", meaning: "classroom", category: "School", example: "Les élèves sont dans la salle de classe.", exampleMeaning: "The students are in the classroom." },
  { french: "plus", meaning: "more, plus (maths)", category: "Adverbs", example: "Je veux plus de café. / Deux plus deux font quatre.", exampleMeaning: "I want more coffee. / Two plus two equals four." },
  { french: "comprend", meaning: "includes, understand, include", category: "Verbs", example: "Il comprend la leçon. / Le prix comprend le petit déjeuner.", exampleMeaning: "He understands the lesson. / The price includes breakfast." },
  { french: "apprennent", meaning: "are learning, learn, study", category: "Verbs", example: "Ils apprennent le français.", exampleMeaning: "They are learning French." },
  { french: "comprennent", meaning: "understand", category: "Verbs", example: "Ils comprennent la question.", exampleMeaning: "They understand the question." },
  { french: "est-ce qu'", meaning: "is, do, does", category: "Questions", example: "Est-ce qu'il pleut ?", exampleMeaning: "Is it raining?" },
  { french: "apprend", meaning: "learns, is studying, learn", category: "Verbs", example: "Elle apprend l'espagnol.", exampleMeaning: "She is learning Spanish." },
  { french: "élève", meaning: "student", category: "School", example: "C'est un bon élève.", exampleMeaning: "He is a good student." },
  { french: "tout", meaning: "everything, all, right", category: "Other", example: "Tout va bien. / J'ai tout compris.", exampleMeaning: "Everything is fine. / I understood everything." },
  { french: "comprenez", meaning: "understand", category: "Verbs", example: "Vous comprenez ?", exampleMeaning: "Do you understand?" },
  { french: "est-ce que", meaning: "do, did, does", category: "Questions", example: "Est-ce que tu viens ?", exampleMeaning: "Are you coming?" },
  { french: "apprenez", meaning: "learn, study, are studying", category: "Verbs", example: "Vous apprenez vite.", exampleMeaning: "You learn quickly." },
  { french: "septembre", meaning: "September", category: "Months", example: "La rentrée est en septembre.", exampleMeaning: "Back to school is in September." },
  { french: "apprends", meaning: "are studying, are learning, hear", category: "Verbs", example: "J'apprends l'anglais.", exampleMeaning: "I am learning English." },
  { french: "comprends", meaning: "understand", category: "Verbs", example: "Je comprends ce que tu dis.", exampleMeaning: "I understand what you're saying." },
  { french: "matière", meaning: "material, subject", category: "School", example: "Quelle est ta matière préférée ?", exampleMeaning: "What is your favorite subject?" },
  { french: "dictionnaire", meaning: "dictionary", category: "School", example: "J'utilise un dictionnaire.", exampleMeaning: "I use a dictionary." },
  { french: "examen", meaning: "quiz, exam, test", category: "School", example: "J'ai un examen demain.", exampleMeaning: "I have an exam tomorrow." },
  { french: "apprendre", meaning: "to learn", category: "Verbs", example: "Je veux apprendre le français.", exampleMeaning: "I want to learn French." },
  { french: "comprendre", meaning: "to understand", category: "Verbs", example: "Je commence à comprendre.", exampleMeaning: "I'm starting to understand." },
  { french: "cours", meaning: "class, course", category: "School", example: "J'ai un cours de français.", exampleMeaning: "I have a French class." },
  { french: "leçon", meaning: "lesson", category: "School", example: "C'est une leçon difficile.", exampleMeaning: "It's a difficult lesson." },
  { french: "facile", meaning: "easy", category: "Adjectives", example: "C'est facile à faire.", exampleMeaning: "It's easy to do." },
  { french: "difficile", meaning: "difficult, hard, challenging", category: "Adjectives", example: "C'est un problème difficile.", exampleMeaning: "It's a difficult problem." },
  { french: "année", meaning: "year", category: "Time", example: "Bonne année !", exampleMeaning: "Happy New Year!" },
  { french: "cet", meaning: "this, that, this (before vowel)", category: "Other", example: "Cet homme est grand.", exampleMeaning: "This man is tall." },
  { french: "été", meaning: "been, summer, was", category: "Seasons", example: "J'ai été en France. / L'été est chaud.", exampleMeaning: "I have been to France. / Summer is hot." },
  { french: "faire de la plongée", meaning: "to scuba dive", category: "Activities", example: "J'aime faire de la plongée.", exampleMeaning: "I like to scuba dive." },
  { french: "janvier", meaning: "January", category: "Months", example: "Janvier est le premier mois de l'année.", exampleMeaning: "January is the first month of the year." },
  { french: "faire du ski", meaning: "to ski", category: "Activities", example: "Je vais faire du ski cet hiver.", exampleMeaning: "I'm going skiing this winter." },
  { french: "faire un voyage", meaning: "to take a trip", category: "Travel", example: "Je veux faire un voyage en Europe.", exampleMeaning: "I want to take a trip to Europe." },
  { french: "février", meaning: "February", category: "Months", example: "Février est le mois le plus court.", exampleMeaning: "February is the shortest month." },
  { french: "montagne", meaning: "mountain, mountains", category: "Nature", example: "J'aime la montagne.", exampleMeaning: "I like the mountains." },
  { french: "hiver", meaning: "winter", category: "Seasons", example: "Il fait froid en hiver.", exampleMeaning: "It's cold in winter." },
  { french: "temps", meaning: "time, weather, tense", category: "Time", example: "Il fait beau temps. / Je n'ai pas le temps.", exampleMeaning: "The weather is nice. / I don't have time." },
  { french: "mois", meaning: "month", category: "Time", example: "Il y a douze mois dans une année.", exampleMeaning: "There are twelve months in a year." },
  { french: "lui", meaning: "him, her, it", category: "Pronouns", example: "Je lui parle.", exampleMeaning: "I'm talking to him/her." },
  { french: "passer", meaning: "to spend, to pass", category: "Verbs", example: "Je vais passer du temps avec ma famille. / Passe-moi le sel.", exampleMeaning: "I'm going to spend time with my family. / Pass me the salt." },
  { french: "rester", meaning: "to stay", category: "Verbs", example: "Je vais rester à la maison.", exampleMeaning: "I'm going to stay at home." },
  { french: "photo", meaning: "picture, photo, photograph", category: "Other", example: "C'est une belle photo.", exampleMeaning: "It's a beautiful picture." },
 { french: "partir", meaning: "to leave", category: "Verbs", example: "Je vais partir en vacances.", exampleMeaning: "I'm going to leave on vacation." },
  { french: "demain", meaning: "tomorrow", category: "Time", example: "Je te verrai demain.", exampleMeaning: "I'll see you tomorrow." },
  { french: "voir", meaning: "to see", category: "Verbs", example: "Je veux te voir.", exampleMeaning: "I want to see you." },
  { french: "week-end", meaning: "weekend", category: "Time", example: "Bon week-end !", exampleMeaning: "Have a good weekend!" },
  { french: "prochain", meaning: "next, upcoming", category: "Time", example: "La semaine prochaine, je serai en vacances.", exampleMeaning: "Next week, I'll be on vacation." },
{ french: "céréales", meaning: "cereal", category: "Food", example: "Je mange des céréales au petit déjeuner.", exampleMeaning: "I eat cereal for breakfast." },
{ french: "adorent", meaning: "love", category: "Verbs", example: "Ils adorent le chocolat.", exampleMeaning: "They love chocolate." },
{ french: "prendre", meaning: "getting, make, take", category: "Verbs", example: "Je vais prendre un café. / Elle prend des photos.", exampleMeaning: "I'm going to have a coffee. / She's taking pictures." },
{ french: "yaourt", meaning: "yogurt", category: "Food", example: "Je mange un yaourt.", exampleMeaning: "I'm eating a yogurt." },
{ french: "fraise", meaning: "strawberry", category: "Food", example: "J'aime les fraises.", exampleMeaning: "I like strawberries." },
{ french: "café au lait", meaning: "coffee with milk", category: "Drinks", example: "Je prends un café au lait.", exampleMeaning: "I'll have a coffee with milk." },
{ french: "minérale", meaning: "mineral", category: "Other", example: "Je bois de l'eau minérale.", exampleMeaning: "I drink mineral water." },
{ french: "boit", meaning: "is drinking, drinks", category: "Verbs", example: "Il boit du jus d'orange.", exampleMeaning: "He is drinking orange juice." },
{ french: "jus d'orange", meaning: "orange juice", category: "Drinks", example: "Je voudrais un jus d'orange.", exampleMeaning: "I would like an orange juice." },
{ french: "l'eau", meaning: "water", category: "Drinks", example: "Je bois de l'eau.", exampleMeaning: "I drink water." },
{ french: "confiture", meaning: "jam, marmalade, preserve", category: "Food", example: "Je mange de la confiture avec du pain.", exampleMeaning: "I eat jam with bread." },
{ french: "de la brioche", meaning: "some brioche", category: "Food", example: "Je voudrais de la brioche.", exampleMeaning: "I would like some brioche." },
{ french: "de la confiture", meaning: "jam", category: "Food", example: "Il y a de la confiture sur la table.", exampleMeaning: "There is jam on the table." },
{ french: "du sucre", meaning: "some sugar", category: "Food", example: "Je mets du sucre dans mon café.", exampleMeaning: "I put sugar in my coffee." },
{ french: "déteste", meaning: "hate, hates", category: "Verbs", example: "Je déteste les lundis.", exampleMeaning: "I hate Mondays." },
{ french: "préfères", meaning: "prefer", category: "Verbs", example: "Tu préfères le thé ou le café ?", exampleMeaning: "Do you prefer tea or coffee?" },
{ french: "brioche", meaning: "brioche", category: "Food", example: "La brioche est délicieuse.", exampleMeaning: "The brioche is delicious." },
{ french: "beurre", meaning: "butter, (I) butter, (you) butter!", category: "Food", example: "Je mets du beurre sur mon pain.", exampleMeaning: "I put butter on my bread." },
{ french: "miel", meaning: "honey", category: "Food", example: "J'aime le miel dans mon thé.", exampleMeaning: "I like honey in my tea." },
{ french: "du miel", meaning: "honey", category: "Food", example: "Il y a du miel dans le placard.", exampleMeaning: "There is honey in the cupboard." },
{ french: "préfère", meaning: "prefer, prefers", category: "Verbs", example: "Je préfère le chocolat.", exampleMeaning: "I prefer chocolate." },
{ french: "bois", meaning: "drink, are drinking, drinks", category: "Verbs", example: "Je bois du café tous les matins.", exampleMeaning: "I drink coffee every morning." },
{ french: "détestes", meaning: "hate", category: "Verbs", example: "Tu détestes les épinards ?", exampleMeaning: "Do you hate spinach?" },
{ french: "du café", meaning: "coffee", category: "Drinks", example: "Voulez-vous du café ?", exampleMeaning: "Would you like some coffee?" },
{ french: "du thé", meaning: "(some) tea, tea", category: "Drinks", example: "Je prends du thé.", exampleMeaning: "I'm having tea." },
{ french: "au petit déjeuner", meaning: "at breakfast", category: "Meals", example: "Je mange des céréales au petit déjeuner.", exampleMeaning: "I eat cereal for breakfast." },
{ french: "adore", meaning: "loves, love", category: "Verbs", example: "J'adore les vacances.", exampleMeaning: "I love vacations." },
{ french: "du lait", meaning: "milk", category: "Drinks", example: "Je mets du lait dans mon café.", exampleMeaning: "I put milk in my coffee." },
{ french: "nageons", meaning: "swim, are swimming", category: "Verbs", example: "Nous nageons dans la piscine.", exampleMeaning: "We are swimming in the pool." },
{ french: "dessinez", meaning: "draw", category: "Verbs", example: "Vous dessinez très bien.", exampleMeaning: "You draw very well." },
{ french: "nager", meaning: "to swim", category: "Verbs", example: "J'aime nager en été.", exampleMeaning: "I like to swim in the summer." },
{ french: "dessines", meaning: "(you) take shape/are taking shape, (you) design, (you) draw/are drawing", category: "Verbs", example: "Tu dessines un portrait.", exampleMeaning: "You are drawing a portrait." },
{ french: "nagent", meaning: "swim, are swimming", category: "Verbs", example: "Ils nagent dans la mer.", exampleMeaning: "They are swimming in the sea." },
{ french: "nage", meaning: "swim, am swimming, swims", category: "Verbs", example: "Je nage tous les jours.", exampleMeaning: "I swim every day." },
{ french: "dessiner", meaning: "to draw", category: "Verbs", example: "J'aime dessiner des paysages.", exampleMeaning: "I like to draw landscapes." },
{ french: "étudier", meaning: "to study", category: "Verbs", example: "Je vais étudier à la bibliothèque.", exampleMeaning: "I'm going to study at the library." },
{ french: "étudions", meaning: "study, are studying", category: "Verbs", example: "Nous étudions le français.", exampleMeaning: "We are studying French." },
{ french: "écouter", meaning: "to listen to, to listen", category: "Verbs", example: "J'aime écouter de la musique.", exampleMeaning: "I like to listen to music." },
{ french: "chanter", meaning: "to sing", category: "Verbs", example: "J'aime chanter sous la douche.", exampleMeaning: "I like to sing in the shower." },
{ french: "chantes", meaning: "sing, are singing", category: "Verbs", example: "Tu chantes très bien.", exampleMeaning: "You sing very well." },
{ french: "chante", meaning: "am singing, sings, sing", category: "Verbs", example: "Elle chante une chanson.", exampleMeaning: "She is singing a song." },
{ french: "écoutes", meaning: "are listening to, listen to, listen", category: "Verbs", example: "Tu écoutes la radio.", exampleMeaning: "You are listening to the radio." },
{ french: "visitez", meaning: "are visiting, visit", category: "Verbs", example: "Vous visitez le musée.", exampleMeaning: "You are visiting the museum." },
{ french: "visitent", meaning: "visit, are visiting", category: "Verbs", example: "Ils visitent Paris.", exampleMeaning: "They are visiting Paris." },
{ french: "danse", meaning: "am dancing, is dancing, dances", category: "Verbs", example: "Elle danse le tango.", exampleMeaning: "She dances the tango." },
{ french: "danser", meaning: "to dance", category: "Verbs", example: "J'aime danser.", exampleMeaning: "I like to dance." },
{ french: "danses", meaning: "(you) dance/are dancing, dance, dances", category: "Verbs", example: "Tu danses bien.", exampleMeaning: "You dance well." },
{ french: "marches", meaning: "are walking, steps, walk", category: "Verbs", example: "Tu marches vite.", exampleMeaning: "You walk fast." },
{ french: "marche", meaning: "work, walks, is walking", category: "Verbs", example: "Il marche dans le parc. / La machine marche bien.", exampleMeaning: "He is walking in the park. / The machine works well." },
{ french: "attendre", meaning: "wait for, waiting, wait", category: "Verbs", example: "J'attends le bus.", exampleMeaning: "I'm waiting for the bus." },
{ french: "en retard", meaning: "late", category: "Time", example: "Je suis en retard.", exampleMeaning: "I am late." },
{ french: "pouvez-vous", meaning: "can you", category: "Questions", example: "Pouvez-vous m'aider ?", exampleMeaning: "Can you help me?" },
{ french: "bagage", meaning: "luggage, bag", category: "Travel", example: "J'ai un bagage.", exampleMeaning: "I have a bag/piece of luggage." },
{ french: "vol", meaning: "theft, flight, robbery", category: "Travel", example: "J'ai un vol pour Paris. / Il y a eu un vol.", exampleMeaning: "I have a flight to Paris. / There was a theft/robbery." },
{ french: "question", meaning: "question", category: "Questions", example: "J'ai une question.", exampleMeaning: "I have a question." },
{ french: "venez-vous", meaning: "are you, do you come", category: "Questions", example: "D'où venez-vous ?", exampleMeaning: "Where are you from?" },
{ french: "Afrique", meaning: "Africa", category: "Places", example: "Je viens d'Afrique.", exampleMeaning: "I come from Africa." },
{ french: "nation", meaning: "nation", category: "Other", example: "La France est une nation.", exampleMeaning: "France is a nation." },
{ french: "quelle", meaning: "what an, what a, what", category: "Questions", example: "Quelle heure est-il ? / Quelle belle journée !", exampleMeaning: "What time is it? / What a beautiful day!" },
{ french: "destination", meaning: "destination", category: "Travel", example: "Quelle est votre destination ?", exampleMeaning: "What is your destination?" },
{ french: "nationalité", meaning: "nationality", category: "Other", example: "Quelle est votre nationalité ?", exampleMeaning: "What is your nationality?" },
{ french: "profession", meaning: "profession", category: "Work", example: "Quelle est votre profession ?", exampleMeaning: "What is your profession?" },
{ french: "Sénégal", meaning: "Senegal", category: "Places", example: "Je viens du Sénégal.", exampleMeaning: "I come from Senegal." },
{ french: "voyagez-vous", meaning: "are you traveling", category: "Questions", example: "Pourquoi voyagez-vous ?", exampleMeaning: "Why are you traveling?" },
{ french: "venez", meaning: "come, are coming", category: "Verbs", example: "Vous venez avec nous ?", exampleMeaning: "Are you coming with us?" },
{ french: "quel", meaning: "which", category: "Questions", example: "Quel est ton nom ?", exampleMeaning: "What is your name?" },
{ french: "prénom", meaning: "first name", category: "Other", example: "Quel est votre prénom ?", exampleMeaning: "What is your first name?" },
{ french: "nom", meaning: "name, last name", category: "Other", example: "Quel est votre nom de famille ?", exampleMeaning: "What is your last name?" },
{ french: "manger", meaning: "to eat, eating, eaten", category: "Verbs", example: "Je vais manger une pizza.", exampleMeaning: "I'm going to eat a pizza." },
{ french: "voulez-vous", meaning: "do you want", category: "Questions", example: "Que voulez-vous boire ?", exampleMeaning: "What do you want to drink?" },
{ french: "boire", meaning: "to drink, drinking", category: "Verbs", example: "Je veux boire de l'eau.", exampleMeaning: "I want to drink water." },
{ french: "quelque chose", meaning: "something", category: "Other", example: "Je veux manger quelque chose.", exampleMeaning: "I want to eat something." },
{ french: "voyagez", meaning: "travel, are traveling", category: "Verbs", example: "Vous voyagez souvent ?", exampleMeaning: "Do you travel often?" },
{ french: "pouvez", meaning: "can, may", category: "Verbs", example: "Vous pouvez répéter, s'il vous plaît ?", exampleMeaning: "Can you repeat, please?" },
{ french: "madame", meaning: "ma'am, Mrs., Ms.", category: "Other", example: "Bonjour, madame.", exampleMeaning: "Hello, ma'am." },
{ french: "excusez-moi", meaning: "excuse me", category: "Other", example: "Excusez-moi, monsieur.", exampleMeaning: "Excuse me, sir." },
{ french: "mademoiselle", meaning: "miss", category: "Other", example: "Bonjour, mademoiselle.", exampleMeaning: "Hello, miss." },
{ french: "monsieur", meaning: "sir, gentleman, man", category: "Other", example: "Bonjour, monsieur.", exampleMeaning: "Hello, sir." },
{ french: "de rien", meaning: "you're welcome", category: "Other", example: "Merci ! - De rien.", exampleMeaning: "Thank you! - You're welcome." },
{ french: "salle de bain", meaning: "bathroom", category: "Places", example: "Où est la salle de bain ?", exampleMeaning: "Where is the bathroom?" },
{ french: "trop de", meaning: "too much, too many", category: "Other", example: "Il y a trop de bruit.", exampleMeaning: "There is too much noise." },
{ french: "trop", meaning: "too many, too, too much", category: "Other", example: "C'est trop cher.", exampleMeaning: "It's too expensive." },
{ french: "sel", meaning: "salt", category: "Food", example: "Passe-moi le sel, s'il te plaît.", exampleMeaning: "Pass me the salt, please." },
{ french: "de l'après-midi", meaning: "in the afternoon", category: "Time", example: "Je travaille l'après-midi.", exampleMeaning: "I work in the afternoon." },
{ french: "placard", meaning: "closet, cupboard, cabinet", category: "Household", example: "Le balai est dans le placard.", exampleMeaning: "The broom is in the closet." },
{ french: "s'il te plaît", meaning: "please", category: "Other", example: "Un café, s'il te plaît.", exampleMeaning: "A coffee, please." },
{ french: "un peu de", meaning: "a little", category: "Other", example: "Je veux un peu de sucre.", exampleMeaning: "I want a little sugar." },
{ french: "sucre", meaning: "sugar, sugar cube, piece of sugar", category: "Food", example: "Il y a du sucre dans le café.", exampleMeaning: "There is sugar in the coffee." },
{ french: "beaucoup de", meaning: "a lot of", category: "Other", example: "J'ai beaucoup de travail.", exampleMeaning: "I have a lot of work." },
{ french: "lait", meaning: "milk", category: "Drinks", example: "Il y a du lait dans le frigo.", exampleMeaning: "There is milk in the fridge." },
{ french: "plaît", meaning: "like, enjoy, pleases", category: "Other", example: "S'il vous plaît. / Ça me plaît.", exampleMeaning: "Please. / I like it." },
{ french: "frigo", meaning: "fridge", category: "Household", example: "Le lait est dans le frigo.", exampleMeaning: "The milk is in the fridge." },
{ french: "du soir", meaning: "at night, evenings, p.m", category: "Time", example: "Je travaille souvent le soir.", exampleMeaning: "I often work at night." },
{ french: "il est", meaning: "he's, it's", category: "Other", example: "Il est tard.", exampleMeaning: "It's late." },
{ french: "devez", meaning: "have to, must, need to", category: "Verbs", example: "Vous devez partir.", exampleMeaning: "You must leave." },
{ french: "du matin", meaning: "morning, in the morning, a.m.", category: "Time", example: "Je me lève tôt le matin.", exampleMeaning: "I get up early in the morning." },
{ french: "horloge", meaning: "clock", category: "Time", example: "L'horloge sonne midi.", exampleMeaning: "The clock strikes noon." },
{ french: "rentre", meaning: "go back, fits, is going home", category: "Verbs", example: "Je rentre à la maison.", exampleMeaning: "I'm going home." },
{ french: "tôt", meaning: "early", category: "Time", example: "Je me couche tôt.", exampleMeaning: "I go to bed early." },
{ french: "tard", meaning: "late", category: "Time", example: "Il est tard.", exampleMeaning: "It's late." },
{ french: "rentrer", meaning: "go back, go home to, go home", category: "Verbs", example: "Je vais rentrer chez moi.", exampleMeaning: "I'm going to go home." },
{ french: "heure", meaning: "time, hour", category: "Time", example: "Quelle heure est-il ?", exampleMeaning: "What time is it?" },
{ french: "sors", meaning: "get out, leave, are coming out", category: "Verbs", example: "Je sors ce soir.", exampleMeaning: "I'm going out tonight." },
{ french: "sortir", meaning: "to go out", category: "Verbs", example: "Je vais sortir avec des amis.", exampleMeaning: "I'm going out with friends." },
{ french: "chez", meaning: "to X's place, to X's house, 's", category: "Places", example: "Je vais chez Marie.", exampleMeaning: "I'm going to Marie's place." },
{ french: "midi", meaning: "noon", category: "Time", example: "Il est midi.", exampleMeaning: "It's noon." },
{ french: "avant", meaning: "before, for, beforehand", category: "Time", example: "Je dois partir avant midi.", exampleMeaning: "I have to leave before noon." },
{ french: "minuit", meaning: "midnight", category: "Time", example: "Il est minuit.", exampleMeaning: "It's midnight." },
{ french: "chambre", meaning: "room, bedroom", category: "Places", example: "Ma chambre est grande.", exampleMeaning: "My room is big." },
{ french: "habitez-vous", meaning: "do you live", category: "Questions", example: "Où habitez-vous ?", exampleMeaning: "Where do you live?" },
{ french: "avez-vous", meaning: "do you have", category: "Questions", example: "Avez-vous des enfants ?", exampleMeaning: "Do you have children?" },
{ french: "avec qui", meaning: "with who", category: "Questions", example: "Avec qui parlez-vous ?", exampleMeaning: "Who are you talking to?" },
{ french: "problème", meaning: "problem", category: "Other", example: "Il y a un problème.", exampleMeaning: "There is a problem." },
{ french: "prends-tu", meaning: "do you take", category: "Questions", example: "Que prends-tu au petit déjeuner ?", exampleMeaning: "What do you have for breakfast?" },
{ french: "étudiez-vous", meaning: "do you study", category: "Questions", example: "Qu'est-ce que vous étudiez ?", exampleMeaning: "What are you studying?" },
{ french: "travailles-tu", meaning: "do you work", category: "Questions", example: "Où travailles-tu ?", exampleMeaning: "Where do you work?" },
{ french: "semaine", meaning: "week", category: "Time", example: "Je travaille toute la semaine.", exampleMeaning: "I work all week." },
{ french: "vas-tu", meaning: "are you going", category: "Questions", example: "Où vas-tu ?", exampleMeaning: "Where are you going?" },
{ french: "sont-ils", meaning: "are they, are", category: "Questions", example: "Sont-ils arrivés ?", exampleMeaning: "Have they arrived?" },
{ french: "est-il", meaning: "is he, is it, did he", category: "Questions", example: "Est-il prêt ?", exampleMeaning: "Is he ready?" },
{ french: "belge", meaning: "Belgian", category: "Other", example: "Je suis belge.", exampleMeaning: "I am Belgian." },
{ french: "pourquoi", meaning: "why", category: "Questions", example: "Pourquoi pas ?", exampleMeaning: "Why not?" },
{ french: "aimes-tu", meaning: "are you fond of, do you love, do you like", category: "Questions", example: "Qu'est-ce que tu aimes faire ?", exampleMeaning: "What do you like to do?" },
{ french: "travaillent-elles", meaning: "do they work", category: "Questions", example: "Où travaillent-elles ?", exampleMeaning: "Where do they work?" },
{ french: "parlez-vous", meaning: "do you speak/talk", category: "Questions", example: "Parlez-vous anglais ?", exampleMeaning: "Do you speak English?" },
{ french: "est-elle", meaning: "is it, is she, did she", category: "Questions", example: "Est-elle mariée ?", exampleMeaning: "Is she married?" },
{ french: "maintenant", meaning: "now, nowadays, today", category: "Time", example: "Je dois partir maintenant.", exampleMeaning: "I have to leave now." },
{ french: "êtes-vous", meaning: "are you", category: "Questions", example: "Êtes-vous prêt ?", exampleMeaning: "Are you ready?" },
{ french: "québécois", meaning: "Quebecois, from Quebec", category: "Other", example: "Je suis québécois.", exampleMeaning: "I am from Quebec." },
{ french: "voulez", meaning: "want", category: "Verbs", example: "Vous voulez boire quelque chose ?", exampleMeaning: "Do you want something to drink?" },
{ french: "tous les jours", meaning: "every day, daily", category: "Time", example: "Je travaille tous les jours.", exampleMeaning: "I work every day." },
{ french: "prenez", meaning: "are getting, are having, getting", category: "Verbs", example: "Vous prenez le bus ?", exampleMeaning: "Are you taking the bus?" },
{ french: "achetez", meaning: "buy, are buying", category: "Verbs", example: "Vous achetez des fruits ?", exampleMeaning: "Are you buying fruit?" },
{ french: "baguette", meaning: "baguette, wand", category: "Food", example: "Je voudrais une baguette.", exampleMeaning: "I would like a baguette." },
{ french: "lisez", meaning: "read, are reading", category: "Verbs", example: "Vous lisez ce livre ?", exampleMeaning: "Are you reading this book?" },
{ french: "nos", meaning: "our", category: "Pronouns", example: "Ce sont nos amis.", exampleMeaning: "These are our friends." },
{ french: "avez", meaning: "have, get", category: "Verbs", example: "Vous avez une voiture ?", exampleMeaning: "Do you have a car?" },
{ french: "vos", meaning: "your", category: "Pronouns", example: "Ce sont vos clés ?", exampleMeaning: "Are these your keys?" },
{ french: "allez", meaning: "go, are going, come on", category: "Verbs", example: "Vous allez au cinéma ?", exampleMeaning: "Are you going to the cinema?" },
{ french: "amie", meaning: "friend", category: "Family", example: "C'est mon amie.", exampleMeaning: "She's my friend." },
{ french: "notre", meaning: "our", category: "Pronouns", example: "C'est notre maison.", exampleMeaning: "It's our house." },
{ french: "marié", meaning: "groom, married", category: "Family", example: "Il est marié.", exampleMeaning: "He is married." },
{ french: "ami", meaning: "friend", category: "Family", example: "C'est mon ami.", exampleMeaning: "He's my friend." },
{ french: "votre", meaning: "your", category: "Pronouns", example: "C'est votre livre ?", exampleMeaning: "Is this your book?" },
{ french: "mariée", meaning: "bride, married, got married", category: "Family", example: "Elle est mariée.", exampleMeaning: "She is married." },
{ french: "habitez", meaning: "live, are living", category: "Verbs", example: "Vous habitez ici ?", exampleMeaning: "Do you live here?" },
{ french: "ensemble", meaning: "together, at the same time, cohesion", category: "Other", example: "Nous travaillons ensemble.", exampleMeaning: "We work together." },
{ french: "aimez", meaning: "love (person/pet), like (thing), love", category: "Verbs", example: "Vous aimez le chocolat ?", exampleMeaning: "Do you like chocolate?" },
{ french: "mariés", meaning: "married, bride and groom", category: "Family", example: "Ils sont mariés.", exampleMeaning: "They are married." },
{ french: "étudiez", meaning: "study, are studying", category: "Verbs", example: "Vous étudiez le français ?", exampleMeaning: "Are you studying French?" },
{ french: "vous êtes", meaning: "you're", category: "Other", example: "Vous êtes étudiant ?", exampleMeaning: "Are you a student?" },
{ french: "parlez", meaning: "speak, are speaking, talk", category: "Verbs", example: "Vous parlez anglais ?", exampleMeaning: "Do you speak English?" },
{ french: "cuisinez", meaning: "cook, are cooking", category: "Verbs", example: "Vous cuisinez bien ?", exampleMeaning: "Do you cook well?" },
{ french: "travaillez", meaning: "work, are working", category: "Verbs", example: "Vous travaillez ici ?", exampleMeaning: "Do you work here?" },
{ french: "dansez", meaning: "dance", category: "Verbs", example: "Vous dansez bien.", exampleMeaning: "You dance well." },
{ french: "êtes", meaning: "are", category: "Verbs", example: "Vous êtes français ?", exampleMeaning: "Are you French?" },
{ french: "vous", meaning: "you, yourselves, yourself", category: "Pronouns", example: "Comment allez-vous ?", exampleMeaning: "How are you?" },
{ french: "troisième", meaning: "third, ninth grade", category: "Other", example: "C'est le troisième étage.", exampleMeaning: "It's the third floor." },
{ french: "visiter", meaning: "visiting, to visit, visit", category: "Verbs", example: "Je vais visiter Paris.", exampleMeaning: "I'm going to visit Paris." },
{ french: "lieu", meaning: "place, premises", category: "Places", example: "C'est un beau lieu.", exampleMeaning: "It's a beautiful place." },
{ french: "dangereux", meaning: "dangerous", category: "Adjectives", example: "C'est dangereux de marcher seul la nuit.", exampleMeaning: "It's dangerous to walk alone at night." },
{ french: "trouver", meaning: "to find, find, finding", category: "Verbs", example: "Je ne trouve pas mes clés.", exampleMeaning: "I can't find my keys." },
{ french: "deuxième", meaning: "second", category: "Other", example: "C'est la deuxième fois.", exampleMeaning: "It's the second time." },
{ french: "près", meaning: "near, close, closely", category: "Other", example: "J'habite près d'ici.", exampleMeaning: "I live near here." },
{ french: "loin", meaning: "far, far away", category: "Other", example: "C'est loin d'ici.", exampleMeaning: "It's far from here." },
{ french: "pont", meaning: "bridge", category: "Places", example: "Le pont est magnifique.", exampleMeaning: "The bridge is magnificent." },
{ french: "route", meaning: "road, runs", category: "Places", example: "La route est longue.", exampleMeaning: "The road is long." },
{ french: "près du", meaning: "close to the", category: "Other", example: "Je suis près du cinéma.", exampleMeaning: "I'm close to the cinema." },
{ french: "près de", meaning: "close to", category: "Other", example: "Il habite près de la mer.", exampleMeaning: "He lives close to the sea." },
{ french: "derrière", meaning: "behind, in the back, at the back", category: "Other", example: "Le chat est derrière la porte.", exampleMeaning: "The cat is behind the door." },
{ french: "habiter", meaning: "to live", category: "Verbs", example: "J'habite à Paris.", exampleMeaning: "I live in Paris." },
{ french: "meuble", meaning: "piece of furniture, softer", category: "Household", example: "C'est un beau meuble.", exampleMeaning: "It's a beautiful piece of furniture." },
{ french: "intéressant", meaning: "interesting", category: "Adjectives", example: "C'est un livre intéressant.", exampleMeaning: "It's an interesting book." },
{ french: "immeuble", meaning: "apartment building, building", category: "Places", example: "J'habite dans un grand immeuble.", exampleMeaning: "I live in a big building." },
{ french: "gauche", meaning: "left", category: "Other", example: "Tournez à gauche.", exampleMeaning: "Turn left." },
{ french: "première", meaning: "premiere, first, eleventh grade", category: "Other", example: "C'est la première fois.", exampleMeaning: "It's the first time." },
{ french: "tourner", meaning: "to turn, turn, (to) turn", category: "Verbs", example: "Il faut tourner à droite.", exampleMeaning: "You have to turn right." },
{ french: "à gauche", meaning: "to the left", category: "Other", example: "Le cinéma est à gauche.", exampleMeaning: "The cinema is on the left." },
{ french: "devant", meaning: "in front of, ahead of, before", category: "Other", example: "Il y a un arbre devant la maison.", exampleMeaning: "There is a tree in front of the house." },
{ french: "à droite", meaning: "to the right", category: "Other", example: "La banque est à droite.", exampleMeaning: "The bank is on the right." },
{ french: "marcher", meaning: "work, walking, works", category: "Verbs", example: "Je vais marcher jusqu'au parc. / La machine ne marche plus.", exampleMeaning: "I'm going to walk to the park. / The machine doesn't work anymore." },
{ french: "dois", meaning: "have to, need to, must", category: "Verbs", example: "Je dois partir.", exampleMeaning: "I have to leave." },
{ french: "aller", meaning: "to go, go, going", category: "Verbs", example: "Je vais au marché.", exampleMeaning: "I'm going to the market." },
{ french: "rue", meaning: "street", category: "Places", example: "J'habite dans cette rue.", exampleMeaning: "I live on this street." },
{ french: "important", meaning: "important", category: "Adjectives", example: "C'est très important.", exampleMeaning: "It's very important." },
{ french: "parler", meaning: "speak, to speak, talking", category: "Verbs", example: "Je veux parler français.", exampleMeaning: "I want to speak French." },
{ french: "quatorze", meaning: "fourteen, 14", category: "Numbers", example: "J'ai quatorze ans.", exampleMeaning: "I am fourteen years old." },
{ french: "quinze", meaning: "fifteen, 15", category: "Numbers", example: "Il est quinze heures.", exampleMeaning: "It's three p.m." },
{ french: "ont-ils", meaning: "do they have", category: "Questions", example: "Ont-ils des enfants ?", exampleMeaning: "Do they have children?" },
{ french: "peux", meaning: "am able to, can, may", category: "Verbs", example: "Je peux t'aider.", exampleMeaning: "I can help you." },
{ french: "treize", meaning: "thirteen, 13", category: "Numbers", example: "Elle a treize ans.", exampleMeaning: "She is thirteen years old." },
{ french: "douze", meaning: "twelve, 12", category: "Numbers", example: "Il y a douze mois dans l'année.", exampleMeaning: "There are twelve months in the year." },
{ french: "onze", meaning: "eleven, 11", category: "Numbers", example: "Il est onze heures.", exampleMeaning: "It's eleven o'clock." },
{ french: "travaillons", meaning: "work, are working", category: "Verbs", example: "Nous travaillons ensemble.", exampleMeaning: "We work together." },
{ french: "travailler", meaning: "to work", category: "Verbs", example: "Je vais travailler demain.", exampleMeaning: "I'm going to work tomorrow." },
{ french: "dix", meaning: "ten, 10", category: "Numbers", example: "J'ai dix doigts.", exampleMeaning: "I have ten fingers." },
{ french: "neuf", meaning: "nine, new, brand new", category: "Numbers", example: "J'ai neuf ans.", exampleMeaning: "I am nine years old." },
{ french: "travailles", meaning: "work, are working", category: "Verbs", example: "Tu travailles beaucoup.", exampleMeaning: "You work a lot." },
{ french: "huit", meaning: "eight, 8", category: "Numbers", example: "Il est huit heures.", exampleMeaning: "It's eight o'clock." },
{ french: "sept", meaning: "seven, 7", category: "Numbers", example: "Il y a sept jours dans une semaine.", exampleMeaning: "There are seven days in a week." },
{ french: "six", meaning: "six, 6", category: "Numbers", example: "J'ai six chats.", exampleMeaning: "I have six cats." },
{ french: "cinq", meaning: "five, 5", category: "Numbers", example: "J'ai cinq doigts à la main.", exampleMeaning: "I have five fingers on my hand." },
{ french: "quatre", meaning: "four, 4", category: "Numbers", example: "Il y a quatre saisons.", exampleMeaning: "There are four seasons." },
{ french: "trois", meaning: "three, 3", category: "Numbers", example: "J'ai trois frères.", exampleMeaning: "I have three brothers." },
{ french: "deux", meaning: "two, 2", category: "Numbers", example: "J'ai deux sœurs.", exampleMeaning: "I have two sisters." },
{ french: "un", meaning: "a, an, one", category: "Numbers", example: "J'ai un chien.", exampleMeaning: "I have a dog." },
{ french: "zéro", meaning: "zero, 0", category: "Numbers", example: "Il fait zéro degré.", exampleMeaning: "It's zero degrees." },
{ french: "travaille", meaning: "am working, works, work", category: "Verbs", example: "Je travaille à la maison. / Il travaille dans un bureau.", exampleMeaning: "I work at home. / He works in an office." },
{ french: "où", meaning: "where", category: "Questions", example: "Où habites-tu ?", exampleMeaning: "Where do you live?" },
{ french: "comment", meaning: "how", category: "Questions", example: "Comment allez-vous ?", exampleMeaning: "How are you?" },
{ french: "ici", meaning: "here", category: "Places", example: "Je suis ici.", exampleMeaning: "I am here." },
{ french: "là", meaning: "there, here", category: "Places", example: "Il est là.", exampleMeaning: "He is there." },
{ french: "gare", meaning: "train station", category: "Places", example: "Je vais à la gare.", exampleMeaning: "I'm going to the train station." },
{ french: "hôpital", meaning: "hospital", category: "Places", example: "Il travaille à l'hôpital.", exampleMeaning: "He works at the hospital." },
{ french: "poste", meaning: "post office, position", category: "Places", example: "Je vais à la poste.", exampleMeaning: "I'm going to the post office." },
{ french: "l'école", meaning: "school", category: "Places", example: "Je vais à l'école.", exampleMeaning: "I'm going to school." },
{ french: "l'université", meaning: "university", category: "Places", example: "Elle étudie à l'université.", exampleMeaning: "She studies at the university." },
{ french: "magasin", meaning: "store, shop", category: "Places", example: "Je vais au magasin.", exampleMeaning: "I'm going to the store." },
{ french: "supermarché", meaning: "supermarket", category: "Places", example: "Je fais les courses au supermarché.", exampleMeaning: "I'm shopping at the supermarket." },
{ french: "marché", meaning: "market", category: "Places", example: "Je vais au marché.", exampleMeaning: "I'm going to the market." },
{ french: "bibliothèque", meaning: "library", category: "Places", example: "Je vais à la bibliothèque.", exampleMeaning: "I'm going to the library." },
{ french: "musée", meaning: "museum", category: "Places", example: "Je visite le musée.", exampleMeaning: "I'm visiting the museum." },
{ french: "cinéma", meaning: "cinema, movie theater", category: "Places", example: "Je vais au cinéma.", exampleMeaning: "I'm going to the cinema." },
{ french: "restaurant", meaning: "restaurant", category: "Places", example: "Je mange au restaurant.", exampleMeaning: "I'm eating at the restaurant." },
{ french: "café", meaning: "coffee, café, coffee shop", category: "Places", example: "Je prends un café au café.", exampleMeaning: "I'm having a coffee at the café." },
{ french: "parc", meaning: "park", category: "Places", example: "Je me promène dans le parc.", exampleMeaning: "I'm walking in the park." },
{ french: "jardin", meaning: "garden", category: "Places", example: "Je suis dans le jardin.", exampleMeaning: "I'm in the garden." },
{ french: "plage", meaning: "beach", category: "Places", example: "Je vais à la plage.", exampleMeaning: "I'm going to the beach." },
{ french: "banque", meaning: "bank", category: "Places", example: "Je vais à la banque.", exampleMeaning: "I'm going to the bank." },
{ french: "ville", meaning: "city, town", category: "Places", example: "J'habite en ville.", exampleMeaning: "I live in the city." },
{ french: "village", meaning: "village", category: "Places", example: "J'habite dans un village.", exampleMeaning: "I live in a village." },
{ french: "pays", meaning: "country", category: "Places", example: "Je viens de ce pays.", exampleMeaning: "I come from this country." },
{ french: "maison", meaning: "house, home", category: "Places", example: "Je suis à la maison.", exampleMeaning: "I'm at home." },
{ french: "appartement", meaning: "apartment, flat", category: "Places", example: "J'habite dans un appartement.", exampleMeaning: "I live in an apartment." },
{ french: "piscine", meaning: "swimming pool", category: "Places", example: "Je nage à la piscine.", exampleMeaning: "I'm swimming at the pool." },
{ french: "bonjour", meaning: "hello, good morning, good day", category: "Greetings", example: "Bonjour, madame.", exampleMeaning: "Hello, madam." },
{ french: "bonsoir", meaning: "good evening, good night", category: "Greetings", example: "Bonsoir, monsieur.", exampleMeaning: "Good evening, sir." },
{ french: "au revoir", meaning: "goodbye", category: "Greetings", example: "Au revoir, à bientôt.", exampleMeaning: "Goodbye, see you soon." },
{ french: "à bientôt", meaning: "see you soon", category: "Greetings", example: "À bientôt, j'espère.", exampleMeaning: "See you soon, I hope." },
{ french: "salut", meaning: "hi, bye, cheers", category: "Greetings", example: "Salut, ça va ?", exampleMeaning: "Hi, how are you?" },
{ french: "oui", meaning: "yes", category: "Other", example: "Oui, je comprends.", exampleMeaning: "Yes, I understand." },
{ french: "non", meaning: "no", category: "Other", example: "Non, merci.", exampleMeaning: "No, thank you." },
{ french: "merci", meaning: "thank you, thanks", category: "Other", example: "Merci beaucoup !", exampleMeaning: "Thank you very much!" },
{ french: "beaucoup", meaning: "a lot, much, very much", category: "Adverbs", example: "Merci beaucoup !", exampleMeaning: "Thank you very much!" },
{ french: "s'il vous plaît", meaning: "please", category: "Other", example: "Un café, s'il vous plaît.", exampleMeaning: "A coffee, please." },
{ french: "pardon", meaning: "sorry, pardon, excuse me", category: "Other", example: "Pardon, je ne comprends pas.", exampleMeaning: "Sorry, I don't understand." },
{ french: "bien", meaning: "good, well", category: "Adverbs", example: "Je vais bien, merci.", exampleMeaning: "I'm fine, thank you." },
{french: "je vais", meaning: "I'm going; I'm doing; I will; I am going", category: "Verbs", example: "Je vais bien", exampleMeaning: "I am doing well" },
{ french: "et", meaning: "and", category: "Other", example: "Toi et moi.", exampleMeaning: "You and I." },
{ french: "je", meaning: "I", category: "Pronouns", example: "Je suis étudiant.", exampleMeaning: "I am a student." },
{ french: "tu", meaning: "you (informal singular)", category: "Pronouns", example: "Tu es mon ami.", exampleMeaning: "You are my friend." },
{ french: "il", meaning: "he, it", category: "Pronouns", example: "Il est grand.", exampleMeaning: "He is tall." },
{ french: "elle", meaning: "she, it", category: "Pronouns", example: "Elle est belle.", exampleMeaning: "She is beautiful." },
{ french: "nous", meaning: "we, us", category: "Pronouns", example: "Nous sommes heureux.", exampleMeaning: "We are happy." },
{ french: "ils", meaning: "they (masculine or mixed)", category: "Pronouns", example: "Ils sont gentils.", exampleMeaning: "They are kind." },
{ french: "elles", meaning: "they (feminine)", category: "Pronouns", example: "Elles sont intelligentes.", exampleMeaning: "They are intelligent." },
{ french: "je suis", meaning: "I am", category: "Verbs", example: "Je suis fatigué.", exampleMeaning: "I am tired." },
{ french: "tu es", meaning: "you are (informal singular)", category: "Verbs", example: "Tu es gentil.", exampleMeaning: "You are kind." },
{ french: "il est", meaning: "he is, it is", category: "Verbs", example: "Il est professeur.", exampleMeaning: "He is a teacher." },
{ french: "elle est", meaning: "she is, it is", category: "Verbs", example: "Elle est étudiante.", exampleMeaning: "She is a student." },
{ french: "nous sommes", meaning: "we are", category: "Verbs", example: "Nous sommes amis.", exampleMeaning: "We are friends." },
{ french: "ils sont", meaning: "they are (masculine or mixed)", category: "Verbs", example: "Ils sont frères.", exampleMeaning: "They are brothers." },
{ french: "elles sont", meaning: "they are (feminine)", category: "Verbs", example: "Elles sont sœurs.", exampleMeaning: "They are sisters." },
{ french: "j'ai", meaning: "I have", category: "Verbs", example: "J'ai un chat.", exampleMeaning: "I have a cat." },
{ french: "tu as", meaning: "you have (informal singular)", category: "Verbs", example: "Tu as un chien.", exampleMeaning: "You have a dog." },
{ french: "il a", meaning: "he has, it has", category: "Verbs", example: "Il a une voiture.", exampleMeaning: "He has a car." },
{ french: "elle a", meaning: "she has, it has", category: "Verbs", example: "Elle a une maison.", exampleMeaning: "She has a house." },
{ french: "nous avons", meaning: "we have", category: "Verbs", example: "Nous avons des enfants.", exampleMeaning: "We have children." },
{ french: "ils ont", meaning: "they have (masculine or mixed)", category: "Verbs", example: "Ils ont des livres.", exampleMeaning: "They have books." },
{ french: "elles ont", meaning: "they have (feminine)", category: "Verbs", example: "Elles ont des fleurs.", exampleMeaning: "They have flowers." },
{ french: "ce", meaning: "this, that, it", category: "Other", example: "Ce livre est intéressant.", exampleMeaning: "This book is interesting." },
{ french: "cette", meaning: "this, that", category: "Other", example: "Cette fleur est belle.", exampleMeaning: "This flower is beautiful." },
{ french: "ces", meaning: "these, those", category: "Other", example: "Ces chaussures sont chères.", exampleMeaning: "These shoes are expensive." },
{ french: "mon", meaning: "my (masculine singular)", category: "Pronouns", example: "C'est mon livre.", exampleMeaning: "It's my book." },
{ french: "ma", meaning: "my (feminine singular)", category: "Pronouns", example: "C'est ma voiture.", exampleMeaning: "It's my car." },
{ french: "mes", meaning: "my (plural)", category: "Pronouns", example: "Ce sont mes amis.", exampleMeaning: "These are my friends." },
{ french: "ton", meaning: "your (informal singular, masculine)", category: "Pronouns", example: "C'est ton chapeau ?", exampleMeaning: "Is this your hat?" },
{ french: "ta", meaning: "your (informal singular, feminine)", category: "Pronouns", example: "C'est ta sœur ?", exampleMeaning: "Is this your sister?" },
{ french: "tes", meaning: "your (informal singular, plural)", category: "Pronouns", example: "Ce sont tes affaires ?", exampleMeaning: "Are these your things?" },
{ french: "son", meaning: "his, her, its (masculine singular)", category: "Pronouns", example: "C'est son chien.", exampleMeaning: "It's his/her dog." },
{ french: "sa", meaning: "his, her, its (feminine singular)", category: "Pronouns", example: "C'est sa maison.", exampleMeaning: "It's his/her house." },
{ french: "ses", meaning: "his, her, its (plural)", category: "Pronouns", example: "Ce sont ses enfants.", exampleMeaning: "These are his/her children." },
{ french: "un homme", meaning: "a man", category: "People", example: "C'est un homme gentil.", exampleMeaning: "He's a kind man." },
{ french: "une femme", meaning: "a woman, a wife", category: "People", example: "C'est une femme intelligente.", exampleMeaning: "She's an intelligent woman." },
{ french: "un garçon", meaning: "a boy, a waiter", category: "People", example: "C'est un garçon mignon.", exampleMeaning: "He's a cute boy." },
{ french: "une fille", meaning: "a girl, a daughter", category: "People", example: "C'est une fille sympathique.", exampleMeaning: "She's a nice girl." },
{ french: "un enfant", meaning: "a child", category: "People", example: "C'est un enfant heureux.", exampleMeaning: "He/She is a happy child." },
{ french: "des enfants", meaning: "children", category: "People", example: "Ce sont des enfants sages.", exampleMeaning: "They are well-behaved children." },
{ french: "un frère", meaning: "a brother", category: "Family", example: "J'ai un frère.", exampleMeaning: "I have a brother." },
{ french: "une sœur", meaning: "a sister", category: "Family", example: "J'ai une sœur.", exampleMeaning:"I have a sister." },
{ french: "un père", meaning: "a father", category: "Family", example: "Mon père est grand.", exampleMeaning: "My father is tall." },
{ french: "une mère", meaning: "a mother", category: "Family", example: "Ma mère est gentille.", exampleMeaning: "My mother is kind." },
{ french: "des parents", meaning: "parents, relatives", category: "Family", example: "Mes parents sont adorables.", exampleMeaning: "My parents are lovely." },
{ french: "la famille", meaning: "the family", category: "Family", example: "J'aime ma famille.", exampleMeaning: "I love my family." },
{ french: "un ami", meaning: "a friend (male)", category: "People", example: "C'est un bon ami.", exampleMeaning: "He's a good friend." },
{ french: "une amie", meaning: "a friend (female)", category: "People", example: "C'est une bonne amie.", exampleMeaning: "She's a good friend." },
{ french: "des amis", meaning: "friends", category: "People", example: "J'ai beaucoup d'amis.", exampleMeaning: "I have a lot of friends." },
{ french: "grand", meaning: "big, tall, large", category: "Adjectives", example: "C'est un grand arbre.", exampleMeaning: "It's a tall tree." },
{ french: "grande", meaning: "big, tall, large (feminine)", category: "Adjectives", example: "C'est une grande maison.", exampleMeaning: "It's a big house." },
{ french: "petit", meaning: "small, little, short", category: "Adjectives", example: "C'est un petit chien.", exampleMeaning: "It's a small dog." },
{ french: "petite", meaning: "small, little, short (feminine)", category: "Adjectives", example: "C'est une petite fille.", exampleMeaning: "She's a little girl." },
{ french: "bon", meaning: "good, right, correct", category: "Adjectives", example: "C'est un bon livre.", exampleMeaning: "It's a good book." },
{ french: "bonne", meaning: "good, right, correct (feminine)", category: "Adjectives", example: "C'est une bonne idée.", exampleMeaning: "It's a good idea." },
{ french: "mauvais", meaning: "bad, wrong", category: "Adjectives", example: "C'est un mauvais film.", exampleMeaning: "It's a bad movie." },
{ french: "mauvaise", meaning: "bad, wrong (feminine)", category: "Adjectives", example: "C'est une mauvaise nouvelle.", exampleMeaning: "It's bad news." },
{ french: "nouveau", meaning: "new", category: "Adjectives", example: "C'est un nouveau restaurant.", exampleMeaning: "It's a new restaurant." },
{ french: "nouvel", meaning: "new (before vowel or mute h)", category: "Adjectives", example: "C'est un nouvel ami.", exampleMeaning: "He is a new friend." },
{ french: "nouvelle", meaning: "new (feminine)", category: "Adjectives", example: "C'est une nouvelle voiture.", exampleMeaning: "It's a new car." },
{ french: "jeune", meaning: "young", category: "Adjectives", example: "C'est un jeune homme.", exampleMeaning: "He's a young man." },
{ french: "vieille", meaning: "old (feminine)", category: "Adjectives", example: "C'est une vieille dame", exampleMeaning: "She is an old lady." }
];